CREATE TABLE worlds(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL,
  description text NOT NULL,
  date_system varchar(8) NOT NULL DEFAULT 'AD'
);

CREATE TABLE characters(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(1000) NOT NULL,
  birth_year integer NOT NULL,
  birth_month integer NOT NULL,
  birth_day integer NOT NULL,
  description text,
  world_id integer NOT NULL REFERENCES worlds(id) ON DELETE CASCADE
);

CREATE TYPE land_type AS ENUM ('continent', 'island', 'archipelago', 'other');

CREATE TABLE landmasses(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(200) NOT NULL,
  type land_type NOT NULL,
  description text,
  world_id integer NOT NULL REFERENCES worlds(id) ON DELETE CASCADE
);

CREATE TYPE nation_type AS ENUM ('country', 'city-state', 'other');

CREATE TABLE nations(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  world_id integer NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,
  landmass_id integer NOT NULL REFERENCES landmasses(id) ON DELETE CASCADE,
  name varchar(200) UNIQUE NOT NULL,
  type nation_type NOT NULL,
  population integer,
  area integer,
  description text
);

CREATE TYPE water_type AS ENUM ('ocean', 'lake', 'river', 'other');

CREATE TABLE water_bodies(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(200) NOT NULL,
  world_id integer NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,
  description text,
  landmass_id integer REFERENCES landmasses(id) ON DELETE CASCADE
);

CREATE TABLE settlements(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  world_id integer NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,
  nation_id integer REFERENCES nations(id) ON DELETE CASCADE,
  population integer,
  description text,
  name varchar(200) NOT NULL
);

CREATE TABLE other_places(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  world_id integer NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,
  description text,
  name varchar(200) NOT NULL
);

CREATE TABLE events(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  world_id integer NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,
  name varchar(1250) NOT NULL,
  description text,
  start_year integer NOT NULL,
  start_month integer,
  start_day integer,
  end_year integer,
  end_month integer,
  end_day integer
);

CREATE TABLE characters_events(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  character_id integer NOT NULL REFERENCES characters(id) ON DELETE CASCADE,
  event_id integer NOT NULL REFERENCES events(id) ON DELETE CASCADE
);

CREATE TABLE places_events(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  world_id integer NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,
  event_id integer NOT NULL REFERENCES events(id) ON DELETE CASCADE,
  landmass_id integer REFERENCES landmasses(id) ON DELETE CASCADE,
  nation_id integer REFERENCES nations(id) ON DELETE CASCADE,
  settlement_id integer REFERENCES settlements(id) ON DELETE CASCADE,
  water_body_id integer REFERENCES water_bodies(id) ON DELETE CASCADE,
  other_place_id integer REFERENCES other_places(id) ON DELETE CASCADE,
  CHECK (landmass_id IS NOT NULL OR nation_id IS NOT NULL OR settlement_id IS NOT NULL OR water_body_id IS NOT NULL OR other_place_id IS NOT NULL)
);

