CREATE TABLE worlds(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text UNIQUE NOT NULL,
  description text NOT NULL,
  date_system varchar(8) NOT NULL DEFAULT 'AD'
);

CREATE TABLE characters(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(1000) NOT NULL,
  birth_year integer NOT NULL,
  birth_month integer NOT NULL,
  birth_day integer NOT NULL,
  description text,
  world_id integer NOT NULL REFERENCES worlds(id) ON DELETE CASCADE
);

CREATE TYPE land_type AS ENUM ('continent', 'island', 'archipelago', 'other');

CREATE TABLE landmasses(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(200) NOT NULL,
  type land_type NOT NULL,
  description text,
  world_id integer NOT NULL REFERENCES worlds(id) ON DELETE CASCADE
);

CREATE TYPE nation_type AS ENUM ('country', 'city-state', 'other');

CREATE TABLE nations(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  world_id integer NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,
  landmass_id integer NOT NULL REFERENCES landmasses(id) ON DELETE CASCADE,
  type nation_type NOT NULL,
  population integer,
  area integer,
  description text
);

CREATE TYPE water_type AS ENUM ('ocean', 'lake', 'river');

CREATE TABLE water_bodies(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(200) NOT NULL,
  world_id integer NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,
  description text,
  landmass_id integer REFERENCES landmasses(id) ON DELETE CASCADE
);

CREATE TABLE settlements(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  world_id integer NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,
  landmass_id integer NOT NULL REFERENCES landmasses(id) ON DELETE CASCADE,
  
)

CREATE TABLE other_places(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  world_id integer NOT NULL REFERENCES worlds(id) ON DELETE CASCADE,
  description text
);